<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function spptu_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function spptu_menu() {

	$items['spptu/new'] = array (
      'title' => 'SPP TU',
	  'description' => 'SPP TU',
	  'title callback' => 'spptu_title_callback',	  
      'page callback' => 'spptu_new_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spptu_new_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['spptu/edit'] = array (
      'title' => 'SPP TU',
	  'description' => 'SPP TU',
	  'title callback' => 'spptu_title_callback',	  
      'page callback' => 'spptu_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spptu_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );


    $items['spptu/delete'] = array (
      'title' => 'Hapus SPP',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('spptu_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'spptu_delete_form.php',
      'type' => MENU_CALLBACK,
    );	

    return $items;
}


function spptu_title_callback() {
	return t('SPP TU');
}

function spptuarsip_title_callback() {
    return t('Daftar SPP TU');
}

