<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function register_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function register_menu() {

	$items['cetakregister'] = array (
      'title' => 'Register SP2D',
	  'description' => 'Register SP2D',
      'page callback' => 'register_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['cetakregisterall'] = array (
      'title' => 'Register SP2D',
	  'description' => 'Register SP2D',
      'page callback' => 'register_all_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_all_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['cetakregisterkoreksi'] = array (
      'title' => 'Register SP2D Koreksi',
	  'description' => 'Register SP2D Koreksi',
      'page callback' => 'register_koreksi_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_koreksi_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	$items['cetakregisterskpd'] = array (
      'title' => 'Register SP2D SKPD',
	  'description' => 'Register SP2D SKPD',
      'page callback' => 'register_skpd_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_skpd_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    
    $items['cetakregisterspm'] = array (
      'title' => 'Register SPM',
	  'description' => 'Register SPM',
      'page callback' => 'register_spm_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_spm_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    
   $items['cetakregisterspp'] = array (
      'title' => 'Register SPP',
	  'description' => 'Register SPP',
      'page callback' => 'register_spp_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_spp_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
   $items['cetakregisterpajak'] = array (
      'title' => 'Register Pajak',
    'description' => 'Register Pajak',
      'page callback' => 'register_pajak_main',
      //'access arguments' => array ('access content'),
    'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_pajak_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    	$items['rekapregister'] = array (
      'title' => 'Rekap Register SP2D',
	  'description' => 'Rekap Register SP2D',
      'page callback' => 'register_rekapsp2d_main',
      //'access arguments' =Rekap> array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_rekapsp2d_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    
    $items['rekapregisterspm'] = array (
      'title' => 'Rekap Register SPM',
	  'description' => 'Rekap Register SPM',
      'page callback' => 'register_rekapspm_main',
      //'access arguments' =Rekap> array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_rekapspm_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    
    $items['rekapregisterspp'] = array (
      'title' => 'Rekap Register SPP',
	  'description' => 'Rekap Register SPP',
      'page callback' => 'register_rekapspp_main',
      //'access arguments' =Rekap> array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'register_rekapspp_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	
    return $items;
}