<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function sp2dgaji_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function sp2dgaji_menu() {


	$items['sp2dgaji/edit'] = array (
      'title' => 'sp2d Gaji',
	  'description' => 'SP2D Gaji',
	  'title callback' => 'sp2dgaji_title_callback',	  
      'page callback' => 'sp2dgaji_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'sp2dgaji_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['sp2dgajiarsip'] = array (
      'title' => 'Daftar SP2D Gaji',
	  'description' => 'Daftar SP2D Gaji',
	  'title callback' => 'sp2dgajiarsip_title_callback',	  
      'page callback' => 'sp2dgajiarsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'sp2dgajiarsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	

    return $items;
}


function sp2dgaji_title_callback() {
	return t('SP2D Gaji');
}

function sp2dgajiarsip_title_callback() {
    return t('Daftar SP2D Gaji');
}

