<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function sp2dnihil_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function sp2dnihil_menu() {


	$items['sp2dnihil/edit'] = array (
      'title' => 'sp2d Nihil',
	  'description' => 'SP2D Nihil',
	  'title callback' => 'sp2dnihil_title_callback',	  
      'page callback' => 'sp2dnihil_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'sp2dnihil_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['sp2dnihilarsip'] = array (
      'title' => 'Daftar SP2D Nihil',
	  'description' => 'Daftar SP2D Nihil',
	  'title callback' => 'sp2dnihilarsip_title_callback',	  
      'page callback' => 'sp2dnihilarsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'sp2dnihilarsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	

    return $items;
}


function sp2dnihil_title_callback() {
	return t('SP2D Nihil');
}

function sp2dnihilarsip_title_callback() {
    return t('Daftar SP2D Nihil');
}

