<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function sumberdid_perm() {
    return array(
        'access penata content',
		'access sumberdid penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function sumberdid_menu() {

	$items['sumberdid'] = array (
      'title' => 'Sumber Dana',
	  'description' => 'Sumber Dana Edit',
	  //'title callback' => 'sumberdidarsip_title_callback',	  
      'page callback' => 'sumberdid_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'sumberdid_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	

	

	
    return $items;
}



