<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function rekening_perm() {
    return array(
        'access penata content',
		'access rekening penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function rekening_menu() {

	$items['rekening/jenis'] = array (
      'title' => 'Rekening APBD | Jenis',
	  'description' => 'Rekening APBD | Jenis',
	  //'title callback' => 'rekeningarsip_title_callback',	  
      'page callback' => 'rekening_jenis_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'rekening_jenis_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    
	$items['rekening/obyek'] = array (
      'title' => 'Rekening APBD | Obyek',
	  'description' => 'Rekening APBD | Obyek',
	  //'title callback' => 'rekeningarsip_title_callback',	  
      'page callback' => 'rekening_obyek_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'rekening_obyek_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    
	$items['rekening/rincian'] = array (
      'title' => 'Rekening APBD | Rincian',
	  'description' => 'Rekening APBD | Rincian',
	  //'title callback' => 'rekeningarsip_title_callback',	  
      'page callback' => 'rekening_rincian_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'rekening_rincian_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	
    return $items;
}