<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function sppnihil_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function sppnihil_menu() {
 
	$items['gunihilspp/newkeg'] = array (
      'title' => 'SPP GU Nihil | Pilih Kegiatan',
	  'description' => 'SPP GU Nihil | Pilih Kegiatan',
	  //'title callback' => 'gunihil_title_callback',	  
      'page callback' => 'gunihilspp_newkeg_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'gunihilspp_newkeg_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['gunihilspp/newspj'] = array (
      'title' => 'SPP GU Nihil | Pilih SPJ',
	  'description' => 'SPP GU Nihil | Pilih SPJ',
	  //'title callback' => 'gunihil_title_callback',	  
      'page callback' => 'gunihilspp_newspj_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'gunihilspp_newspj_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	 
	$items['gunihilspp/new'] = array (
      'title' => 'SPP GU Nihil',
	  'description' => 'SPP GU Nihil',
	  //'title callback' => 'gunihil_title_callback',	  
      'page callback' => 'gunihilspp_new_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'gunihilspp_new_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	$items['sppnihilarsip'] = array (
      'title' => 'Daftar SPP Nihil',
	  'description' => 'Daftar SPP Nihil',
	  'title callback' => 'sppnihilarsip_title_callback',	  
      'page callback' => 'sppnihilarsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'sppnihilarsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['sppnihil/edit'] = array (
      'title' => 'SPP Nihil',
	  'description' => 'SPP Nihil',
	  'title callback' => 'sppnihil_title_callback',	  
      'page callback' => 'sppnihil_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'sppnihil_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
   $items['sppnihil/delete'] = array (
      'title' => 'Hapus SPP',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('sppnihil_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'sppnihil_delete_form.php',
      'type' => MENU_CALLBACK,
    );	

    return $items;
}


function sppnihilantrian_title_callback() {
    return t('Antrian SPP Nihil');
}

function sppnihil_title_callback() {
	return t('SPP Nihil');
}

function sppnihilarsip_title_callback() {
    return t('Daftar SPP Nihil');
}

