<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function dokumensjp_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function dokumenspj_menu() {
	$items['dokumenspj/new'] = array (
      'title' => 'Dokumen Pendukung SPJ',
	  'description' => 'Dokumen Pendukung SPJ',
	  //'title callback' => 'dokumenspj_title_callback',	  
      'page callback' => 'dokumenspj_new_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'dokumenspj_new_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['dokumenspj/edit'] = array (
      'title' => 'Dokumen Pendukung SPJ',
	  'description' => 'Dokumen Pendukung SPJ',
	  //'title callback' => 'dokumenspj_title_callback',	  
      'page callback' => 'dokumenspj_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'dokumenspj_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['dokumenspjarsip'] = array (
      'title' => 'Daftar Dokumen Pendukung SPJ',
	  'description' => 'Daftar Dokumen Pendukung SPJ',
	  //'title callback' => 'dokumenspj_title_callback',	  
      'page callback' => 'dokumenspj_arsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'dokumenspj_arsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    $items['dokumenspj/delete'] = array (
      'title' => 'Hapus Dokumen Pendukung SPJ',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dokumenspj_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'dokumenspj_delete_form.php',
      'type' => MENU_CALLBACK,
    );	
	 
    return $items;
}

