<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function barangjasa_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function barangjasa_menu() {

	$items['barangjasaspp/newkeg'] = array (
      'title' => 'SPP Barang Jasa | Pilih Kegiatan',
	  'description' => 'SPP Barang Jasa | Pilih Kegiatan',
	  //'title callback' => 'barangjasaspp_title_callback',	  
      'page callback' => 'barangjasaspp_newkeg_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasaspp_newkeg_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['barangjasaspp/newrek'] = array (
      'title' => 'SPP Barang Jasa | Pilih Rekening',
	  'description' => 'SPP Barang Jasa | Pilih Rekening',
	  //'title callback' => 'barangjasaspp_title_callback',	  
      'page callback' => 'barangjasaspp_newrek_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasaspp_newrek_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	$items['barangjasaspp/edit'] = array (
      'title' => 'SPP Barang Jasa',
	  'description' => 'SPP Barang Jasa',
	  //'title callback' => 'barangjasaspp_title_callback',	  
      'page callback' => 'barangjasaspp_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasaspp_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['barangjasaspparsip'] = array (
      'title' => 'Daftar SPP Barang Jasa',
	  'description' => 'Daftar SPP Barang Jasa',
	  //'title callback' => 'barangjasaspp_arsip_title_callback',	  
      'page callback' => 'barangjasaspp_arsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasaspp_arsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    $items['barangjasaspp/delete'] = array (
      'title' => 'Hapus SPP',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('barangjasaspp_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'barangjasaspp_delete_form.php',
      'type' => MENU_CALLBACK,
    );	

	$items['barangjasaspm/edit'] = array (
      'title' => 'SPM Barang Jasa',
	  'description' => 'SPM Barang Jasa',
	  //'title callback' => 'barangjasaspm_title_callback',	  
      'page callback' => 'barangjasaspm_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasaspm_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['barangjasaspmarsip'] = array (
      'title' => 'Daftar SPM Barang Jasa',
	  'description' => 'Daftar SPM Barang Jasa',
	  //'title callback' => 'barangjasaspm_arsip_title_callback',	  
      'page callback' => 'barangjasaspm_arsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasaspm_arsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    $items['barangjasaspm/verify'] = array (
      'title' => 'Verifikasi SPM',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('barangjasaspm_verify_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'barangjasaspm_verify_form.php',
      'type' => MENU_CALLBACK,
    );
	
    $items['barangjasaspm/delete'] = array (
      'title' => 'Hapus SPM',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('barangjasaspm_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'barangjasaspm_delete_form.php',
      'type' => MENU_CALLBACK,
    );	

	$items['barangjasasp2darsip'] = array (
      'title' => 'Daftar SP2D Barang Jasa',
	  'description' => 'Daftar SP2D Barang Jasa',
	  //'title callback' => 'barangjasasp2d_arsip_title_callback',	  
      'page callback' => 'barangjasasp2d_arsip_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasasp2d_arsip_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['barangjasasp2d/edit'] = array (
      'title' => 'SP2D Barang Jasa',
	  'description' => 'SP2D Barang Jasa',
	  //'title callback' => 'barangjasasp2d_title_callback',	  
      'page callback' => 'barangjasasp2d_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasasp2d_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['barangjasakoreksi/edit'] = array (
      'title' => 'SP2D Barang Jasa',
	  'description' => 'SP2D Barang Jasa',
	  //'title callback' => 'barangjasasp2d_title_callback',	  
      'page callback' => 'barangjasasp2dkoreksi_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'barangjasasp2dkoreksi_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
    $items['barangjasasp2d/verify'] = array (
      'title' => 'Verifikasi SP2D',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('barangjasasp2d_verify_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'barangjasasp2d_verify_form.php',
      'type' => MENU_CALLBACK,
    );
	
    $items['barangjasasp2d/delete'] = array (
      'title' => 'Hapus SP2D',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('barangjasasp2d_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'barangjasasp2d_delete_form.php',
      'type' => MENU_CALLBACK,
    );		
    return $items;
}


function barangjasaspp_title_callback() {
	return t('SPP Barang Jasa');
}

function barangjasaspp_arsip_title_callback() {
    return t('Daftar SPP Barang Jasa');
}

function barangjasaspm_title_callback() {
	return t('SPM barangjasa');
}

function barangjasaspm_arsip_title_callback() {
    return t('Daftar SPM barangjasa');
}

function barangjasasp2d_title_callback() {
	return t('SP2D barangjasa');
}

function barangjasasp2d_arsip_title_callback() {
    return t('Daftar SP2D barangjasa');
}
