<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function userskpd_perm() {
    return array(
        'access userskpd content',
		'access laporan userskpd',
	);
}

/**
 * Implementation of hook_menu().
 */

function userskpd_menu() {
//ITEM  (DB Tata U)
	$items['userskpd'] = array (
      'title' => 'Penugasan SKPD',
	  'description' => 'Penugasan SKPD',
	  //'title callback' => 'gantiuang_title_callback',	  
      'page callback' => 'userskpd_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'userskpd_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
    return $items;
}