<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function approved_permission() {
  return array(
    'spmsp2d appproval' => array(
      'title' => t('Approval SPM/SP2D'),
      'description' => t('Approval SPM/SP2D.'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */

function approved_menu() {
	$items['approvedcoba'] = array (
      'title' => 'Approval SPM',
	  'description' => 'Approved',
	  'title callback' => 'approved_title_callback',	  
      'page callback' => 'approvedcoba_main',
      'access arguments' => array ('spmsp2d appproval'),
	  //'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'approvedcoba_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['approved'] = array (
      'title' => 'Approval SPM',
	  'description' => 'Approved',
	  'title callback' => 'approved_title_callback',	  
      'page callback' => 'approved_main',
      'access arguments' => array ('spmsp2d appproval'),
	  //'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'approved_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
    return $items;
}

?>